-- Seed dữ liệu KB mẫu theo cấu trúc PRD (để AI Doctor & tra cứu có dữ liệu)
-- Lưu ý: đây là dữ liệu mẫu minh họa — cần chuyên gia xác thực trước khi dùng chính thức.
INSERT INTO public.kb_entries (plant_type, category, target_part, problem_name, scientific_name, agents, symptoms_description, symptoms_images, severity_levels, farming_method, biological_method, active_ingredients, dosage_notes, source_url, status) VALUES
('sau_rieng', 'benh_hat', 'than', 'Xì mủ / Thối thân', 'Phytophthora palmivora', 'Nấm', 'Nứt dọc thân, chảy mủ trắng/nâu, mô thối, lộ gỗ bên trong.', ARRAY[]::text[], 'Nặng', 'Cạo vết bệnh, khơi rãnh thoát nước, tránh đọng nước.', 'Trichoderma quanh tán, thiên địch.', ARRAY['Metalaxyl','Phosphonate'], 'Quét vết + tưới gốc. REI 30 ngày.', 'https://ppd.gov.vn', 'published'),
('sau_rieng', 'benh_hat', 'la', 'Cháy lá / Chết ngọn', 'Rhizoctonia solani', 'Nấm', 'Cháy khô từ chóp lá lan vào, vân đồng tâm, ranh giới rõ.', ARRAY[]::text[], 'Trung bình', 'Cắt bỏ lá bệnh, tăng thông thoáng.', 'Bacillus subtilis.', ARRAY['Copper Oxychloride','Hexaconazole'], 'Phun lá. REI 7-14 ngày.', 'https://ppd.gov.vn', 'published'),
('cafe', 'benh_hat', 'la', 'Rỉ sắt', 'Hemileia vastatrix', 'Nấm', 'Đốm bột vàng cam mặt dưới lá, rụng lá sớm.', ARRAY[]::text[], 'Trung bình', 'Tỉa cành thông thoáng sau thu hoạch.', 'Nấm đối kháng, vệ sinh vườn.', ARRAY['Hexaconazole','Propiconazole'], 'Phun đầu mùa mưa. REI 30 ngày.', 'https://wasi.org.vn', 'published'),
('cafe', 'dinh_duong', 'la', 'Thiếu Kali (K)', NULL, 'Thiếu vi lượng', 'Mép lá già cháy vàng → khô, cây phát triển kém.', ARRAY[]::text[], 'Trung bình', 'Bón Kali Sulphate, tránh KCl nếu đất mặn.', 'Phân hữu cơ, humic.', ARRAY['Kali Sulphate'], 'Bón gốc, chia nhiều lần.', 'https://wasi.org.vn', 'published'),
('ho_tieu', 'benh_hat', 're', 'Chết nhanh', 'Phytophthora', 'Nấm', 'Héo rũ đột ngột, thối gốc, rụng lá nhanh.', ARRAY[]::text[], 'Nặng', 'Cách ly cây bệnh, rải vôi quanh gốc.', 'Chitosan, Trichoderma.', ARRAY['Metalaxyl + Mancozeb'], 'Tưới gốc. REI 30 ngày.', 'https://wasi.org.vn', 'published'),
('ho_tieu', 'dinh_duong', 're', 'Chết chậm (Tuyến trùng)', NULL, 'Tuyến trùng', 'Vàng lá từ từ, rễ u sưng, cây suy yếu dần.', ARRAY[]::text[], 'Trung bình', 'Bón hữu cơ hoai, hạn chế tưới úng.', 'Nấm đối kháng.', ARRAY['Chitosan'], 'Xử lý đất định kỳ.', 'https://wasi.org.vn', 'published')
ON CONFLICT DO NOTHING;
